### ISSUE TITLE
how to customize so it shows under the stock text and not override the text?

### ISSUE THREAD

**Issue by raykai** [anttiviljami/woocommerce-custom-availability#3]
Hi,
i would like to start by saying thx for this addon.

i was wandering if there could be a way to keep showing the Stock Quantity in front end and have this plugin show the custom availability text for products under the line of the stock quantity that its on now so that it would not override the availability text set by WC but show this plugin text under it.

Exp of what i need it to do:
1 in stock (also available on backorder)
Usually ships in 1-2 weeks (Need this on an other line under the stock text front end.)

Instead of removing the 1 in stock (also available on backorder) and just showing say: 
Usually ships in 1-2 weeks (like its doing now)

thx for your time 👍

**Comment by raykai** [comment]
bump

**Comment by anttiviljami** [comment]
I can't see a way to support this functionality universally with WooCommerce. This seems to me like a theme specific thing that would require some code customisation. 

I will however accept suggestions on how to include the current stock availability text and include a custom message with it.

**Comment by syedabuthahirm** [comment]
It's possible..
Now we replaced WooCommerce availability string with our custom string using
`woocommerce_get_availability` filter.
For this issue we could append our string instead replacing it. It will solve this issue. But everyone of them doesn't need this functionality by default. So we need configuration for that.

**Comment by syedabuthahirm** [comment]
#6

**Comment by raykai** [comment]
> It's possible..
> Now we replaced WooCommerce availability string with our custom string using
> woocommerce_get_availability filter.
> For this issue we could append our string instead replacing it. It will solve this issue. But everyone of them doesn't need this functionality by default. So we need configuration for that.

That would be a nice option to have!

**Comment by syedabuthahirm** [comment]
I already coded that functionality take look at #6

**Comment by anttiviljami** [comment]
Thanks, merged #6 !
