### ISSUE TITLE
premade drop-down list of text

### ISSUE THREAD

**Issue by raykai** [anttiviljami/woocommerce-custom-availability#4]
would be nice having a premade drop-down list of text instead of always inserting the text by hand on every product like :
Usually ships in 24 hours:
Usually ships in 2-3 days:
Usually ships in 1-2 weeks:
Limited availability: (This means the product you have chosen to purchase has a very limited stock available. We will inform you by e-mail if any items in your order prove to be unavailable.)
Custom Text (custom text field as it is now where we can enter text that we need to show)

As i posted on an other ticket if you need $ to continue the work on this plugin you chould add this plugin on codecanyon https://codecanyon.net could get payed to continue to work on it with pro version that could have more options as long as its not 60$ and keep the free version on WP plugin list.

i think a lot of ppl would be in need of this plugin if you add a bit more options to it then add it to codecanyon it would sell i think, i know i would buy it.

Only one i can seam to find is https://codecanyon.net/item/woocommerce-availability-scheduler/11649604
it has 207 Sales at 17$ usd maid in one year. But don't seam to do the same as your plugin, this one only shows it in time...

i think a lot of ppl would be in need of your plugin if you add a bit more options to it then add it to codecanyon it would sell i think, i know i would buy it.

**Comment by anttiviljami** [comment]
Thanks @raykai for your suggestion. Please feel free to contribute the code for this.

I'm not interested in making any money off this plugin. As it is GPL licensed, you are free to fork your own version of this plugin and submit it to codecanyon to make some money yourself if you wish.

I will continue to accept code from people using this plugin and keep updating it to the wordpress.org plugin repository.
